# Generated by Django 3.1.7 on 2021-02-28 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receptionist',
            old_name='avatar_url',
            new_name='avatar',
        ),
    ]
